name: Build and Test C# ChatBot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Use latest .NET 8 version

      - name: Restore Dependencies
        run: dotnet restore "chatbot/C# Studies/studies/studies.csproj"  # Adjust this path

      - name: Build Project
        run: dotnet build "chatbot/C# Studies/studies/studies.csproj" --configuration Release --no-restore

      - name: Run Program
        run: dotnet run --project "chatbot/C# Studies/studies/studies.csproj"
